# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin_Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.IntegerField()),
                ('exchange_id', models.IntegerField()),
                ('price_usd', models.FloatField()),
                ('price_inr', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=100)),
                ('coin_abbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Term_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttd_tag_id', models.IntegerField()),
                ('ttd_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('coin_id', models.IntegerField()),
                ('exchange_id', models.IntegerField()),
                ('total_investment_usd', models.FloatField()),
                ('total_investment_inr', models.FloatField()),
                ('units_owned', models.FloatField()),
                ('total_investment_value_usd', models.FloatField()),
                ('total_investment_value_inr', models.FloatField()),
            ],
        ),
    ]
