# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_user_coins_currency_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_coins',
            unique_together=set([('user_id', 'coin_id')]),
        ),
    ]
